title: Edson Arthur Zancheta
# logo: /assets/img/minha.jpeg
description: Data-oriented Mechanical Engineering graduate with hands-on experience in data analysis and process automation.
show_downloads: false
#google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
