title: Edson Arthur Zancheta
logo: /assets/img/profile.jpg # Optional: if you want a logo in the header, some themes use this
description: Data-oriented Mechanical Engineering graduate with hands-on experience in data analysis and process automation.
show_downloads: false
# google_analytics:

remote_theme: sproogen/modern-resume-theme 
plugins:
  - jekyll-remote-theme

# To use a different theme, you would change 'remote_theme'.
# For example, for a CV-focused theme:
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: sharu725/online-cv
# Each theme might have its own specific configuration options.
